---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: {{ .Values.namespace }}
  labels:
    app: hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: {{ .Values.image }}
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-app-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: hello-world-app
