namespace: dev
image: kennyd3d/hello-world-app:latest

# Overrides
environments:
  dev:
    namespace: dev
    image: kennyd3d/hello-world-app:6e4ec18
  qa:
    namespace: qa
    image: kennyd3d/hello-world-app:latest
  stable:
    namespace: stable
    image: kennyd3d/hello-world-app:latest
